# Generated by Django 4.0.2 on 2022-02-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0005_rename_date_created_products_added_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='houseID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userorders',
            old_name='orderID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userwishlist',
            old_name='wishID',
            new_name='id',
        ),
    ]
