# Generated by Django 4.0.2 on 2022-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0007_userorders_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorders',
            name='paymentMethod',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Card Payment', 'Card Payment')], max_length=100),
        ),
    ]
