# Generated by Django 4.0.2 on 2022-02-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0008_alter_userorders_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
