# Generated by Django 4.0.2 on 2022-02-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0009_products_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwishlist',
            old_name='user',
            new_name='userID',
        ),
    ]
