# Generated by Django 4.0.2 on 2022-02-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0010_rename_user_userwishlist_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwishlist',
            old_name='userID',
            new_name='user_id',
        ),
    ]
