# Generated by Django 4.0.2 on 2022-02-25 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0012_rename_user_id_userwishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='userwishlist',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
