# Generated by Django 4.0.2 on 2022-02-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0013_remove_userwishlist_user_userwishlist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
