# Generated by Django 4.0.2 on 2022-02-25 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0014_rename_user_id_userwishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwishlist',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
