# Generated by Django 4.0.2 on 2022-02-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0015_alter_userwishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlogs',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userorders',
            old_name='userID',
            new_name='user',
        ),
    ]
