# Generated by Django 4.0.2 on 2022-02-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingModule', '0016_rename_userid_useraddress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='placed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
